version: '3.3'

services:
  django_api:
    build: .
    env_file:
      - ./.env
    stop_signal: SIGINT
    container_name: django_api
    command: bash -c "sleep 3s;
      cd bike_api;
      python manage.py makemigrations;
      python manage.py migrate;
      python manage.py createsuperuser --noinput;
      python manage.py loaddata users;
      python manage.py loaddata bikes;
      python manage.py runserver 0.0.0.0:8000;"
    volumes:
      - ./dump/app:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery_worker:
    build: .
    env_file:
      - ./.env
    stop_signal: SIGINT
    container_name: celery_worker
    command: bash -c "sleep 5s;
                      cd bike_api;
                      celery -A bike_api worker -l INFO;"
    volumes:
      - ./dump/app:/usr/src/app
    depends_on:
      - db
      - redis
      - django_api


  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    restart: always
    volumes:
      - ./dump/redis:/data

  db:
    container_name: ${DB_CONTAINER_NAME}
    image: postgres:15.0-alpine
    command:
      - "postgres"
      - "-c"
      - "log_statement=all"
    env_file:
      - ./.env
    volumes:
      - ./dump/postgres_db/postgres/postgresql-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: unless-stopped